import argparse
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import time
import os
from sklearn.metrics import mean_absolute_error, r2_score, mean_squared_error

from stgcn_model import STGCN
from data_loader import get_dataloaders


def evaluate(model, data_loader, A_hat, criterion, device, return_preds=False):
    model.eval()
    total_loss = 0.0
    all_preds = []
    all_targets = []
    
    with torch.no_grad():
        for inputs, targets in data_loader:
            inputs, targets = inputs.to(device), targets.to(device)
            outputs = model(A_hat, inputs)
            
            if outputs.shape[-1] == 1:
                outputs = outputs.squeeze(-1)
                
            loss = criterion(outputs, targets)
            total_loss += loss.item() * inputs.size(0)
            
            if return_preds:
                all_preds.append(outputs.cpu().numpy())
                all_targets.append(targets.cpu().numpy())
                
    avg_loss = total_loss / len(data_loader.dataset)
    
    if return_preds:
        return avg_loss, np.concatenate(all_preds, axis=0), np.concatenate(all_targets, axis=0)
    return avg_loss


def train(args):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"Using device: {device}")

    # ==========================
    # 1. Load Data
    # ==========================
    # Calculate absolute path to data dir based on script location
    current_dir = os.path.dirname(os.path.abspath(__file__))
    data_dir_root = os.path.join(current_dir, "..", "..", "data")
    data_dir_clean = os.path.join(data_dir_root, "clean")
    
    # In preprocessing_clean.py, the columns are:
    # 0:aqi, 1:pm25, 2:pm10, 3:co, 4:ma_pm25_24, ...
    train_loader, val_loader, test_loader, train_dataset = get_dataloaders(
        data_dir=data_dir_clean,
        batch_size=args.batch_size,
        seq_len=args.seq_len,
        pre_len=args.pre_len,
        target_col_idx=4  # Predicting ma_pm25_24
    )
    
    # ==========================
    # 2. Graph Adjacency Matrix
    # ==========================
    # Load the real spatial adjacency matrix generated by generate_graph.py
    adj_matrix_path = os.path.join(data_dir_root, "graph_adj_matrix.csv")
    if os.path.exists(adj_matrix_path):
        A = np.loadtxt(adj_matrix_path, delimiter=',')
        print(f"Loaded spatial adjacency matrix from {adj_matrix_path}")
    else:
        print(f"Warning: Adjacency matrix not found at {adj_matrix_path}. Using Identity matrix.")
        num_nodes = 32
        A = np.eye(num_nodes)
        
    # Normalized Adjacency (A_hat) for Graph Conv: A_hat = D^(-1/2) * A * D^(-1/2)
    # Adding self-loops first (A_tilde = A + I) as standard in GCN
    A_tilde = A + np.eye(A.shape[0])
    rowsum = np.sum(A_tilde, axis=1)
    d_inv_sqrt = np.power(rowsum, -0.5).flatten()
    d_inv_sqrt[np.isinf(d_inv_sqrt)] = 0.
    D_inv_sqrt = np.diag(d_inv_sqrt)
    A_hat = A_tilde.dot(D_inv_sqrt).transpose().dot(D_inv_sqrt)
    
    A_hat = torch.FloatTensor(A_hat).to(device)

    # Features: total 17 features after dropping 'time' column
    # [aqi, pm25, pm10, co, ma_pm25_24, rh, dewpt, temp, precip, wind_spd, wind_sin, wind_cos, hour_sin, hour_cos, month_sin, month_cos, is_abnormal_aqi]
    num_features = 17 

    # ==========================
    # 3. Model Setup
    # ==========================
    model = STGCN(
        num_nodes=A.shape[0],
        num_features=num_features,
        num_timesteps_input=args.seq_len,
        num_timesteps_output=args.pre_len
    ).to(device)

    optimizer = optim.Adam(model.parameters(), lr=args.lr)
    criterion = nn.MSELoss()

    # ==========================
    # 4. Training Loop
    # ==========================
    print("Starting training...")
    best_val_loss = float('inf')
    
    for epoch in range(args.epochs):
        start_time = time.time()
        
        model.train()
        train_loss = 0.0
        
        for batch_idx, (inputs, targets) in enumerate(train_loader):
            inputs, targets = inputs.to(device), targets.to(device)
            
            optimizer.zero_grad()
            
            # outputs shape: (batch_size, num_nodes, pre_len)
            # targets shape: (batch_size, num_nodes) -> need to add dimension if pre_len=1
            outputs = model(A_hat, inputs)
            
            if outputs.shape[-1] == 1:
                outputs = outputs.squeeze(-1)
                
            loss = criterion(outputs, targets)
            loss.backward()
            optimizer.step()
            
            train_loss += loss.item() * inputs.size(0)
            
        train_loss = train_loss / len(train_loader.dataset)
        val_loss = evaluate(model, val_loader, A_hat, criterion, device)
        
        print(f'Epoch [{epoch+1}/{args.epochs}], Train Loss: {train_loss:.4f}, Val Loss: {val_loss:.4f}, Time: {(time.time() - start_time):.1f}s')
        
        # Save best model
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            os.makedirs("checkpoints", exist_ok=True)
            torch.save(model.state_dict(), 'checkpoints/best_stgcn.pth')
            print(f'   -> Saved new best model (Val Loss: {best_val_loss:.4f})')

    # ==========================
    # 5. Testing
    # ==========================
    model.load_state_dict(torch.load('checkpoints/best_stgcn.pth', weights_only=True))
    test_loss, test_preds_norm, test_targets_norm = evaluate(model, test_loader, A_hat, criterion, device, return_preds=True)
    
    print(f'\nFinal Test Loss (MSE on normalized data): {test_loss:.4f}')
    
    # Inverse transform to get actual metrics on original scale
    # target_std and target_mean are scalar arrays (float values representing ma_pm25_24 stats)
    target_std = train_dataset.std[4]
    target_mean = train_dataset.mean[4]
    
    test_preds_actual = test_preds_norm * target_std + target_mean
    test_targets_actual = test_targets_norm * target_std + target_mean
    
    # Flatten across (batch_size, num_nodes, pre_len) to compute global metrics
    preds_flat = test_preds_actual.flatten()
    targets_flat = test_targets_actual.flatten()
    
    rmse = np.sqrt(mean_squared_error(targets_flat, preds_flat))
    mae = mean_absolute_error(targets_flat, preds_flat)
    r2 = r2_score(targets_flat, preds_flat)
    
    print(f'Test RMSE (Original Scale ma_pm25_24): {rmse:.2f}')
    print(f'Test MAE  (Original Scale ma_pm25_24): {mae:.2f}')
    print(f'Test R2-Score                        : {r2:.4f}')

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--seq_len', type=int, default=24, help='Length of input historical sequence')
    parser.add_argument('--pre_len', type=int, default=96, help='Prediction horizon (96 hours = 4 days)')
    parser.add_argument('--batch_size', type=int, default=64)
    parser.add_argument('--epochs', type=int, default=50)
    parser.add_argument('--lr', type=float, default=0.001)
    
    args = parser.parse_args()
    train(args)
